#!/bin/bash
docker run --name oracle-19c \
  -p 1521:1521 \
  -e ORACLE_SID=XE \
  -e ORACLE_PWD=abc123 \
  -v /tmp/oracle-19c/oradata/:/opt/oracle/oradata \
  doctorkirk/oracle-19c

# Create user test_user and grant him admin priviledges
CREATE USER test_user IDENTIFIED BY 123456
GRANT DBA TO test_user

# Troubleshooting:
# ERROR: Got minus one from a read call
# https://stackoverflow.com/a/73150106
docker exec oracle-19c echo "DISABLE_OOB=ON" >>/opt/oracle/oradata/dbconfig/XE/sqlnet.ora
